name: Build and run tests (CI)

on: [push, workflow_dispatch]

jobs:
  build_and_run_tests:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Allow gradlew execution
        run: chmod +x gradlew

      - name: Run application
        run: ./gradlew bootRun --args=--spring.profiles.active=local

      - name: Run performance tests
        uses: grafana/k6-action@v0.2.0
        with:
          filename: test.js
          flags: --out json=results.json

      - name: Upload performance test results
        uses: actions/upload-artifact@v3
        with:
          name: k6-report
          path: results.json