name: Build and run tests (CI)

on: [push, workflow_dispatch, pull_request]

jobs:
  build_and_run_tests:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Allow gradlew execution
        run: chmod +x gradlew

      - name: Install k6
        run: |
          curl https://github.com/grafana/k6/releases/download/v0.43.1/k6-v0.43.1-linux-amd64.tar.gz -L | tar xvz --strip-components 1

      - name: Run application
        run: ./gradlew bootRun --args=--spring.profiles.active=local &

      - name: Wait for application to start
        run: sleep 30

      - name: Check connection
        run: curl http://localhost:8080/test?assortmentCategory=1

      - name: Run performance tests
        id: performanceTests
        run: ./k6 run src/main/resources/send_get_assortment_visibility.js --out json=results.json

      - name: Comment PR when performance tests failed
        if: failure() && steps.performanceTests.outcome == 'failure'
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
              Performance tests check failed!
          comment_includes: "Check it"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: ls
        if: success() || failure()
        run: ls -la

      - name: Upload performance test results 1
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: k6-summary-report-html
          path: summary.html

      - name: Upload performance test results 2
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: k6-summary-report-json
          path: results.json